football_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from core.views import *
from news.views import *
from orders.views import *
from products.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_page, name='main_page'),

    path('news/', news_list, name='news_list'),
    path('news/<slug:article_slug>/', article, name='article'),
    path('add_article/', add_article, name='add_article'),

    path('sign_up/', sign_up, name='sign_up'),
    path('sign_in/', sign_in, name='sign_in'),
    path('create_profile/', create_profile, name='create_profile'),
    path('logout/', logout, name='logout'),
    path('my_profile/', my_profile, name='my_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('add_address/', add_address, name='add_address'),
    path('delete_address/', delete_address, name='delete_address'),

    path('my_cart/', my_cart, name='my_cart'),
    path('update_quantity/', update_quantity, name='update_quantity'),
    path('delete_cart_item/', delete_cart_item, name='delete_cart_item'),

    path('confirm_order/', confirm_order, name='confirm_order'),
    path('create_order/', create_order, name='create_order'),
    path('thanks_for_order/<str:order_number>', thanks_for_order, name='thanks_for_order'),
    path('my_orders/', my_orders, name='my_orders'),
    path('order/<str:order_number>/', order_details, name='order_details'),
    path('my_reviews', my_reviews, name='my_reviews'),

    path('all_orders/', all_orders, name='all_orders'),
    path('manage_order/<str:order_number>', manage_order, name='manage_order'),

    path('all_categories', all_categories, name='all_categories'),
    path('categories/<slug:category_slug>', category_products, name='category_products'),
    path('subcategories/<slug:subcategory_slug>/', subcategory_products, name='subcategory_products'),
    path('search_products/', search_products, name='search_products'),
    path('products/<slug:product_slug>/', product_details, name='product_details'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),

    re_path(r'^.*/$', not_found, name='not_found')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
import os

from PIL import Image
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from transliterate import translit

from products.enums import *
from users.models import Profile


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(blank=True, editable=False, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Subcategory(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(blank=True, editable=False, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"


class Country(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(blank=True, editable=False, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Страна"
        verbose_name_plural = "Страны"


class League(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(blank=True, editable=False, unique=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.name} {self.country}'

    def save(self, *args, **kwargs):
        self.slug = f"{slugify(translit(self.name, 'ru', reversed=True))}-{slugify(translit(self.country.name, 'ru',reversed=True))}"
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Лига"
        verbose_name_plural = "Лиги"


class Club(models.Model):
    name = models.CharField(max_length=255)
    league = models.ForeignKey(League, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Клуб"
        verbose_name_plural = "Клубы"


class Product(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    material = models.CharField(max_length=255, choices=Material.get_choices())
    sex = models.CharField(max_length=255, choices=Sex.get_choices())
    color = models.CharField(max_length=255, choices=Color.get_choices())
    slug = models.SlugField(blank=True, editable=False, unique=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='product_thumbnails/', blank=True, null=True)

    def __str__(self):
        return f'{self.name} {self.club}'

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(translit(f'{self.name} {self.club}', 'ru', reversed=True))

            self.image.name = f'{self.slug}.png'
            super().save(*args, **kwargs)

            image_path = os.path.join(settings.MEDIA_ROOT, self.image.name)
            thumbnail_path = os.path.join(settings.MEDIA_ROOT,
                                          f'product_thumbnails/{self.slug}_thumbnail.png')
            with Image.open(image_path) as img:
                img.thumbnail((50, 50))
                img.save(thumbnail_path, 'png')

            self.thumbnail.name = f'product_thumbnails/{self.slug}_thumbnail.png'

        else:
            old_product = Product.objects.get(pk=self.pk)
            if self.image != old_product.image:
                self.image.name = f'{self.slug}.png'
                super().save(*args, **kwargs)

                image_path = os.path.join(settings.MEDIA_ROOT, self.image.name)
                thumbnail_path = os.path.join(settings.MEDIA_ROOT, f'product_thumbnails/{self.slug}_thumbnail.png')

                with Image.open(image_path) as img:
                    img.thumbnail((50, 50))
                    img.save(thumbnail_path, 'png')

                self.thumbnail.name = f'product_thumbnails/{self.slug}_thumbnail.png'

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class ProductUnit(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        properties = self.productunitproperty_set.all()
        property_values = ', '.join([f'{prop.property.name}: {prop.property_value}' for prop in properties])

        return f'{self.product}. {property_values}'

    class Meta:
        verbose_name = "Единица товара"
        verbose_name_plural = "Единицы товаров"
        unique_together = ('product', 'quantity')


class Property(models.Model):
    name = models.CharField(max_length=255)
    choices = models.CharField(max_length=255, choices=BaseProperty.get_subclasses(), default='Нет')

    def __str__(self):
        return self.name

    def get_property_values_for_product(self, product: Product):
        product_units = product.productunit_set.all().filter(quantity__gt=0)
        values_dict = {}

        for product_unit in product_units:
            try:
                value = ProductUnitProperty.objects.get(
                    product_unit=product_unit,
                    property=self
                ).property_value
                values_dict[value] = product_unit.id
            except ProductUnitProperty.DoesNotExist:
                pass

        return values_dict

    class Meta:
        verbose_name = "Характеристика"
        verbose_name_plural = "Характеристики"


class ProductUnitProperty(models.Model):
    product_unit = models.ForeignKey(ProductUnit, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    property_value = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.property}: {self.property_value} у товара {self.product_unit.product}'

    class Meta:
        verbose_name = "Хар-ка товара"
        verbose_name_plural = "Хар-ки товара"


class Review(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    user_hidden = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    stars = models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
    text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Отзыв пользователя {self.profile} на товар {self.product}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

products/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404

from orders.models import *
from products.utils import get_filtered_and_paginated_products


def all_categories(request):
    categories = Category.objects.all()

    context = {
        'title': 'Все категории',
        'categories': categories
    }

    return render(request=request,
                  template_name='all_categories.html',
                  context=context)


def category_products(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    subcategories = Subcategory.objects.filter(category=category)
    products = Product.objects.filter(subcategory__in=subcategories)

    context = get_filtered_and_paginated_products(request, products)

    context.update({
        'title': category.name,
        'category': category,
    })

    return render(request=request,
                  template_name='products_list.html',
                  context=context)


def subcategory_products(request, subcategory_slug):
    subcategory = get_object_or_404(Subcategory, slug=subcategory_slug)
    products = Product.objects.filter(subcategory=subcategory)

    context = get_filtered_and_paginated_products(request, products)

    context.update({
        'title': subcategory.name,
        'subcategory': subcategory,
    })

    return render(request=request,
                  template_name='products_list.html',
                  context=context)


def product_details(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    product_units = ProductUnit.objects.filter(product=product).filter(quantity__gt=0)
    cart = get_object_or_404(Cart, user=request.user)
    cart_objects = CartItem.objects.filter(cart=cart)

    properties_values = {}
    valid_properties = set()

    for product_unit in product_units:
        properties_for_unit = Property.objects.filter(productunitproperty__product_unit=product_unit)
        values_dict = {}

        for prop in properties_for_unit:
            try:
                value = ProductUnitProperty.objects.get(
                    product_unit=product_unit,
                    property=prop
                ).property_value
                values_dict[prop] = value
                valid_properties.add(prop)
            except ProductUnitProperty.DoesNotExist:
                pass

        properties_values[product_unit.id] = values_dict

    valid_properties = Property.objects.filter(id__in=[prop.id for prop in valid_properties])

    in_cart = any(cart_object.product_unit.product == product for cart_object in cart_objects)

    context = {
        'title': product.name,
        'product': product,
        'properties_values': properties_values,
        'valid_properties': valid_properties,
        'product_units': product_units,
        'reviews': Review.objects.filter(product=product),
        'in_cart': in_cart,
    }

    return render(request=request,
                  template_name='product_details.html',
                  context=context)


def add_to_cart(request):
    if request.method == 'POST':
        product_unit_id = request.POST.get('product_unit_id')
        quantity = int(request.POST.get('quantity', 1))

        product_unit = get_object_or_404(ProductUnit, id=product_unit_id)
        cart = Cart.objects.get(user=request.user)

        new_cart_item = CartItem.objects.create(
            product_unit=product_unit,
            quantity=quantity,
            cart=cart
        )

        new_cart_item.quantity = quantity
        new_cart_item.save()
        cart.calculate_total_price()

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})


def search_products(request):
    query = request.GET.get('search-input', '')
    query_capitalized = query.capitalize()
    query_uppered = query.upper()
    products = Product.objects.filter(
        Q(name__icontains=query) |
        Q(club__name__icontains=query) |
        Q(club__league__name__icontains=query) |
        Q(club__league__country__name__icontains=query) |
        Q(name__icontains=query_capitalized) |
        Q(club__name__icontains=query_capitalized) |
        Q(club__league__name__icontains=query_capitalized) |
        Q(club__league__country__name__icontains=query_capitalized) |
        Q(name__icontains=query_uppered) |
        Q(club__name__icontains=query_uppered) |
        Q(club__league__name__icontains=query_uppered) |
        Q(club__league__country__name__icontains=query_uppered)
    )

    context = get_filtered_and_paginated_products(request, products, default_sort='price_asc')

    context.update({
        'title': f'Товары по запросу: {query}',
        'query': query,
    })

    return render(request=request,
                  template_name='products_list.html',
                  context=context)


def my_reviews(request):
    if not request.user.is_authenticated:
        return redirect('sign_in')

    user = request.user
    user_profile = get_object_or_404(Profile, user=user)
    user_reviews = Review.objects.filter(profile=user_profile).order_by('-created_at')

    context = {
        'title': 'Мои отзывы',
        'user': user,
        'profile': user_profile,
        'reviews': user_reviews
    }

    return render(request=request,
                  template_name='my_reviews.html',
                  context=context)

products/templates/all_categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <p class="category-path">
        <a href="{% url 'main_page' %}">Главная</a> /</p>
    <h1>Все категории</h1>
    <ul class="categories">
        {% for category in categories %}
            <li>
                <a href="{% url 'category_products' category_slug=category.slug %}">
                    <h2>{{ category.name }}</h2></a>
                {% if category.subcategory_set.all %}
                    <ul>
                        {% for subcategory in category.subcategory_set.all %}
                            <li><a class="colored-link" href="{% url 'subcategory_products' subcategory_slug=subcategory.slug %}">
                                {{ subcategory.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <link rel="stylesheet" href="{% static 'css/all_categories.css' %}">
{% endblock %}

products/templates/product_details.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load static %}
{% block content %}
    <p class="product-path">
        <a href="{% url 'category_products' category_slug=product.subcategory.category.slug %}">
            {{ product.subcategory.category }}</a> / <a
            href="{% url 'subcategory_products' subcategory_slug=product.subcategory.slug %}">
        {{ product.subcategory }}
    </a>
    </p>
    <h1>{{ product }}</h1>
    <div class="product-main">
        <div class="product-image">
            <img src="{{ product.image.url }}" alt=""/>
        </div>
        <div class="product-info">
            <h2 class="price">{{ product.price }} ₽</h2>
            <p><b>Пол:</b> {{ product.get_sex_display|lower }}</p>
            <p><b>Цвет:</b> {{ product.get_color_display|lower }}</p>
            <p><b>Материал:</b> {{ product.get_material_display|lower }}</p>

            {% for property in valid_properties %}
                <p>
                    <b>{{ property.name }}:</b>
                    <label for="property-choice">
                        <select name="property-choice">
                            {% for product_unit_id, values in properties_values.items %}
                                {% if property in values %}
                                    {% for key, value in values.items %}
                                        <option value="{{ value }}"
                                                data-product-unit-id="{{ product_unit_id }}">{{ value }}</option>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </select>
                    </label>
                </p>
            {% endfor %}
            {% if in_cart %}
                <a class="submit-button" id="add-to-cart-btn" style="display: none;">Добавить в корзину</a>
                <a class="submit-button in-cart" href="{% url 'my_cart' %}">В корзине</a>
            {% else %}
                <a class="submit-button" id="add-to-cart-btn">Добавить в корзину</a>
                <a class="submit-button in-cart" href="{% url 'my_cart' %}" style="display: none;">В корзине</a>
            {% endif %}
        </div>
    </div>
    <div class="description">
        <h2>Описание</h2>
        <p class="product-description">{{ product.description }}</p>
    </div>
    <div class="reviews">
        <h2>Отзывы</h2>
        {% if reviews %}
            {% for review in reviews %}
                <div class="review">
                    {% if not review.user_hidden %}
                        <h3>{{ review.profile.first_name }}</h3>
                    {% else %}
                        <h3>Пользователь скрыл свои данные</h3>
                    {% endif %}
                    <h5>{% for _ in review.stars|times %}
                        <i class="em em-star" aria-role="presentation" aria-label="WHITE MEDIUM STAR"></i>
                    {% endfor %}</h5>
                    <p>{{ review.text }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>Еще никто не оставил отзывов на этот товар <i class="em em-face_with_rolling_eyes"
                                                             aria-role="presentation"
                                                             aria-label="FACE WITH ROLLING EYES"></i></p>
        {% endif %}
    </div>

    <link rel="stylesheet" href="{% static 'css/product_details.css' %}">
    <script src="{% static 'js/product_details.js' %}"></script>
{% endblock %}

products/templates/products_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if subcategory %}
        <p class="category-path">
            <a href="{% url 'category_products' category_slug=subcategory.category.slug %}">
                {{ subcategory.category }}</a> /</p>
    {% else %}
        <p class="category-path">
            <a href="{% url 'all_categories' %}">
                Все категории</a> /</p>
    {% endif %}
    <h1>{{ title }}</h1>

    <div class="subcategory-main">
        {% if products %}
            <div class="products-window">
                <div class="sorting">
                    <form action="" method="get" id="sortForm">
                        <input type="hidden" name="search-input" value="{{ query }}">
                        <p>Сортировать по:
                            <label>
                                <select name="sort_by" onchange="document.getElementById('sortForm').submit()">
                                    <option value="price_asc"
                                            {% if request.GET.sort_by == "price_asc" %}selected{% endif %}>
                                        цене по возрастанию
                                    </option>
                                    <option value="price_desc"
                                            {% if request.GET.sort_by == "price_desc" %}selected{% endif %}>
                                        цене по убыванию
                                    </option>
                                </select>
                            </label>
                        </p>
                    </form>
                </div>
                <div class="product-grid">
                    {% for product in products %}
                        <div class="product-item">
                            <a class="colored-link" href="{% url 'product_details' product_slug=product.slug %}">
                                <div class="product-image">
                                    <img src="{{ product.image.url }}" alt="">
                                </div>
                                <h4>{{ product }}</h4>
                            </a>
                            <p><b>Цена:</b> {{ product.price }} ₽</p>
                        </div>
                    {% endfor %}
                </div>
                <div class="pagination">
                    {% if products.paginator.num_pages > 10 %}
                        {% if products.number <= 6 %}
                            {% for i in products.paginator.page_range|slice:":7" %}
                                {% if i == products.number %}
                                    <span class="current-page">{{ i }}</span>
                                {% else %}
                                    <a href="?page={{ i }}">{{ i }}</a>
                                {% endif %}
                            {% endfor %}
                            <span class="three-dots">...</span>
                            <a href="?page={{ products.paginator.num_pages }}">{{ products.paginator.num_pages }}</a>
                        {% elif products.number >= products.paginator.num_pages|add:"-4" %}
                            <a href="?page=1">1</a>
                            <span class="three-dots">...</span>
                            {% for i in products.paginator.page_range|slice:"-8:" %}
                                {% if i == products.number %}
                                    <span class="current-page">{{ i }}</span>
                                {% else %}
                                    <a href="?page={{ i }}">{{ i }}</a>
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <a href="?page=1">1</a>
                            <span class="three-dots">...</span>
                            {% for i in products.paginator.page_range|slice:"{{ products.number|add:'-3' }}:{{ products.number|add:'3' }}" %}
                                {% if i == products.number %}
                                    <span class="current-page">{{ i }}</span>
                                {% else %}
                                    <a href="?page={{ i }}">{{ i }}</a>
                                {% endif %}
                            {% endfor %}
                            <span class="three-dots">...</span>
                            <a href="?page={{ products.paginator.num_pages }}">{{ products.paginator.num_pages }}</a>
                        {% endif %}
                    {% else %}
                        {% for i in products.paginator.page_range %}
                            {% if i == products.number %}
                                <span class="current-page">{{ i }}</span>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% else %}
            <div><p>К сожалению, на нашем сайте еще нет таких товаров
                <i class="em em-sob" aria-role="presentation" aria-label="LOUDLY CRYING FACE"></i>
            </p>
                <a class="colored-link" href="{% url 'main_page' %}"><b>На главную</b></a></div>
        {% endif %}
    </div>

    <link rel="stylesheet" href="{% static 'css/products_list.css' %}"/>
{% endblock %}

products/templates/subcategory.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <p class="subcategory-path">
        <a href="">{{ subcategory.category }}</a> /</p>
    <h1>{{ subcategory.name }}</h1>

    <div class="subcategory-main">
        <div class="filters-window">

        </div>
        <div class="products-window">
            <div class="filters">
                <form action="" method="get" id="sortForm">
                    <p>Сортировать по:
                        <label>
                            <select name="sort_by" onchange="document.getElementById('sortForm').submit()">
                                <option value="price_asc"
                                        {% if request.GET.sort_by == "price_asc" %}selected{% endif %}>
                                    цене по возрастанию
                                </option>
                                <option value="price_desc"
                                        {% if request.GET.sort_by == "price_desc" %}selected{% endif %}>
                                    цене по убыванию
                                </option>
                            </select>
                        </label>
                    </p>
                </form>
            </div>
            <div class="product-grid">
                {% for product in products %}
                    <div class="product-item">
                        <a class="colored-link" href="{% url 'product_details' product_slug=product.slug %}">
                            <div class="product-image">
                                <img src="{{ product.image.url }}" alt="">
                            </div>
                            <h4>{{ product }}</h4>
                        </a>
                        <p><b>Цена:</b> {{ product.price }} ₽</p>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination">
                {% if products.paginator.num_pages > 10 %}
                    {% if products.number <= 6 %}
                        {% for i in products.paginator.page_range|slice:":7" %}
                            {% if i == products.number %}
                                <span class="current-page">{{ i }}</span>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                        <span class="three-dots">...</span>
                        <a href="?page={{ products.paginator.num_pages }}">{{ products.paginator.num_pages }}</a>
                    {% elif products.number >= products.paginator.num_pages|add:"-4" %}
                        <a href="?page=1">1</a>
                        <span class="three-dots">...</span>
                        {% for i in products.paginator.page_range|slice:"-8:" %}
                            {% if i == products.number %}
                                <span class="current-page">{{ i }}</span>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <a href="?page=1">1</a>
                        <span class="three-dots">...</span>
                        {% for i in products.paginator.page_range|slice:"{{ products.number|add:'-3' }}:{{ products.number|add:'3' }}" %}
                            {% if i == products.number %}
                                <span class="current-page">{{ i }}</span>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                        <span class="three-dots">...</span>
                        <a href="?page={{ products.paginator.num_pages }}">{{ products.paginator.num_pages }}</a>
                    {% endif %}
                {% else %}
                    {% for i in products.paginator.page_range %}
                        {% if i == products.number %}
                            <span class="current-page">{{ i }}</span>
                        {% else %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

    <link rel="stylesheet" href="{% static 'css/subcategory.css' %}"/>
{% endblock %}